CREATE TABLE CUSTOMERS (
  ID INT NOT NULL,
  FIRST_NAME VARCHAR(45) NULL,
  LAST_NAME VARCHAR(45) NULL,
  FAMILY_NAME VARCHAR(45) NULL,
  IPN VARCHAR(10) NULL,
  STATUS INT NOT NULL,
  TYPE INT NOT NULL,
  CREATED_BY INT NOT NULL,
  MODIFIED_BY INT NOT NULL,
  CREATED_TS INT NULL,
  MODIFIED_TS INT NULL,
  PRIMARY KEY (ID))
;
   
CREATE TABLE ACCOUNTS (
  ID INT NOT NULL,
  ACC_CLASS VARCHAR(4) NULL,
  ACC_KEY VARCHAR(1) NULL,
  ACC_SUBACC VARCHAR(9) NULL,
  CUSTOMER_ID INT NOT NULL,
  STATUS INT NOT NULL,
  AMOUNT FLOAT NULL,
  AMOUNT_DYN FLOAT NULL,
  CCY INT NOT NULL,
  CREATED_BY INT NOT NULL,
  MODIFIED_BY INT NOT NULL,
  CREATED_TS INT NULL,
  MODIFIED_TS INT NULL,
  PRIMARY KEY (ID))
;